### PR TITLE
Template editor backspace fix, closes #128

### LINKED ISSUE #128: Backspace doesnt work in filterable select in personalization in fullscreen template editor

### PR DESCRIPTION
**Pull request by radiansz**

### CODE REVIEW

File: src/blocks/templateEditor/templateEditor.js [hunk 1]
```diff
@@ -9,8 +9,11 @@ define(function(require) {
         globalEvents: {
             'keydown': function(event) {
                 var self = this;
-                if(!this.modifiers.fullscreen)
+
+                if (!this.modifiers.fullscreen || event.target.tagName === 'INPUT' || event.target.tagName === 'TEXTAREA') {
```
Comment (rosendi) [inline src/blocks/templateEditor/templateEditor.js]: move it to `isInputTarget`

File: src/blocks/templateEditor/templateEditor.js [hunk 2]
```diff
@@ -9,8 +9,11 @@ define(function(require) {
         globalEvents: {
             'keydown': function(event) {
```
Comment (rosendi) [inline src/blocks/templateEditor/templateEditor.js]: move it to function `removeElement`

**Comment by rosendi** [comment]
LGTM
